# This file manages the GitHub repository security settings

name: Security Policy Configuration
rules:
  # Rule to prevent secret leaks in code
  - id: github-push-protection
    description: Prevent secrets from being committed to the repository
    pattern: >-
      # API Keys
      [A-Za-z0-9-_]{20,}
      # Connection strings
      (Server|Data Source)=(.*);(Database|Initial Catalog)=(.*)
      # Azure Storage account keys
      DefaultEndpointsProtocol=https;AccountName=(.*);AccountKey=(.*);EndpointSuffix=(.*)
      # JWT tokens
      eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*
    severity: high

# Team alert settings for security findings
alerts:
  recipients:
    - security@example.com
    - devteam@example.com
  frequency: immediate
