name: Secret Rotation Check

on:
  schedule:
    # Run weekly on Sunday at midnight
    - cron: '0 0 * * 0'
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-secret-rotation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check secrets age
        id: check-secrets
        run: |
          # This is a placeholder script that would be replaced with actual checking logic
          # In a real implementation, this would query Azure Key Vault and check last rotation dates
          # For demonstration purposes, we're just outputting a message
          echo "Checking secret rotation status..."
          echo "SECRET_CHECK_RESULT=Please review secrets in Azure Key Vault for rotation status" >> $GITHUB_OUTPUT

      - name: Create issue if rotation needed
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = "${{ steps.check-secrets.outputs.SECRET_CHECK_RESULT }}";
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔄 Secret rotation check - Weekly reminder',
              body: `Weekly secret rotation check reminder:

              ${result}

              As per our security policy, please verify that all secrets have been rotated within the last 90 days.
              
              - [ ] Azure Key Vault secrets
              - [ ] Stripe API keys
              - [ ] DALL-E API keys
              - [ ] GitHub secret values
              
              **Note:** This is an automated reminder created by our secret rotation workflow.`
            });
