name: Secret Scanning

on:
  push:
    branches: [ '*' ]
  
jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.63.3
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
